### PR TITLE
Update list of categories, fixes #55

### LINKED ISSUE #55: KeyError: u'burgers'
https://sentry.resmio.com/resmio/portal/issues/2176/

```
KeyError: u'burgers'
(16 additional frame(s) were not displayed)
...
  File "portal/views.py", line 121, in restaurant
    'nearby_restaurants': nearby_restaurants})
  File "portal/templatetags/footer.py", line 47, in footer_category_list
    translate_category(category) ))
  File "portal/categories.py", line 29, in translate_category
    return CATEGORIES[category_id]

KeyError: u'burgers'
```

### PR DESCRIPTION
**Pull request by nsb**

### CODE REVIEW

**Comment by nsb** [comment]
@Atisheh I updated the list.

**Comment by Atisheh** [comment]
@nsb just curious: why don't we want things like sushi in there?

**Comment by nsb** [comment]
I just copied the list from here. https://github.com/resmio/resmio/blob/master/bookoya/models/facility.py#L72-L105 According @JannKleen That is the master list.

**Comment by Atisheh** [comment]
@nsb ahhh I also kinda thought sushi was still a comment. sorry for that :D

**Pull request merged**
